/**
 * Mirrors the API's `enum Permission` (design §16.13). Bit positions must never change or be reused.
 * TODO: generate this file from the API's /permissions/catalog so the two can't drift.
 */
export enum Permission {
  DASHBOARD_PAGE_VIEW = 0,
  DASHBOARD_KPI_VIEW = 1,
  DASHBOARD_CATEGORY_VIEW = 2,
  DASHBOARD_NEAR_BREACH = 3,
  INBOX_PAGE_VIEW = 4,
  INBOX_SCOPE_OWN = 5,
  INBOX_SCOPE_DEPARTMENT = 6,
  INBOX_SCOPE_ALL = 7,
  INBOX_CHAT_REPLY = 8,
  INBOX_CHAT_INTERNAL_VIEW = 9,
  INBOX_ASSIGN_SELF = 10,
  INBOX_ASSIGN_OTHERS = 11,
  INBOX_STATUS_CHANGE = 12,
  INBOX_STATUS_ESCALATE = 13,
  INBOX_STATUS_REOPEN = 14,
  INBOX_ENQUIRY_CREATE = 15,
  INBOX_CUSTOMER_CHAT_VIEW = 16,
  INBOX_CUSTOMER_CHAT_SEARCH_MESSAGES = 17,
  INBOX_TAG_APPLY = 18,
  INBOX_TAG_CREATE_INLINE = 19,
  CUSTOMER_PANEL_CONTACT_VIEW = 20,
  CUSTOMER_PANEL_CONTACT_EDIT = 21,
  SETTINGS_ROLE_MANAGE = 45,
  INBOX_ENQUIRY_EDIT = 46,
  INBOX_STATUS_CHANGE_ANY = 47,
}
